### ISSUE TITLE
The image displayed in the emoji component is blank and cannot be displayed

### ISSUE THREAD

**Issue by MRhanrui** [serebrov/emoji-mart-vue#293]
https://unpkg.com/emoji-datasource-apple@14.0.0/img/apple/sheets-256/64.png
The unresponsive address resulted in blank image display in the emoji component

**Comment by MRhanrui** [comment]
![Uploading 7614F88D-05F6-4374-9D46-70D73B078528.png…]()

**Comment by serebrov** [comment]
This is mentioned in the [readme](https://github.com/serebrov/emoji-mart-vue?tab=readme-ov-file#picker):

### Picker

```js
import data from 'emoji-mart-vue-fast/data/all.json'
import { Picker, EmojiIndex } from 'emoji-mart-vue-fast'
let emojiIndex = new EmojiIndex(data)
```

Import CSS with default styles:

```js
import 'emoji-mart-vue-fast/css/emoji-mart.css'
```

Note: to have a custom look for the picker, either use own css file without including the standard one or add custom styles on top of standard.

**Note: CSS also includes background images for image-based emoji sets (apple, google, twitter, facebook). The images are loaded from the `unpkg.com`. To use self-hosted emojis sheet, override CSS like this**:

```css
/* load twitter sheet from own server */
.emoji-mart-body .emoji-type-image.emoji-set-twitter {
	background-image: url(/img/twitter-5.0.1-sheets-256-64.png);
}
```
