### ISSUE TITLE
Get individual emoji as PNG

### ISSUE THREAD

**Issue by frizurd** [serebrov/emoji-mart-vue#84]
This may also be a feature request...
But are there any easy hacks to get a chosen emoji as an individual PNG image?

All the individual images are available on Unpkg:
https://unpkg.com/browse/emoji-datasource-apple@5.0.1/img/apple/64/

Thanks!

Love the plugin by the way!

**Comment by serebrov** [comment]
@frizurd This component only [uses](https://github.com/serebrov/emoji-mart-vue/blob/master/css/emoji-mart.css#L48) sprites with all emojis on one image, so you can't literally get the image, but you can probably get a file name that you need using `EmojiIndex`.

For example:

```
let emojiData = index.emoji('+1')
console.log(emojiData)
```

Will output this:

```
EmojiData
    colons: ":+1:"
    emoticons: undefined
    id: "+1"
    name: "Thumbs Up Sign"
    native: "👍"
    short_name: "+1"
    short_names: Array(2)
        0: "+1"
        1: "thumbsup"
    skin: 1
    unified: "1f44d"
    _data:
        added_in: "2.0"
        emoticons: undefined
        has_img_apple: true
        has_img_facebook: true
        has_img_google: true
        has_img_twitter: true
        keywords: (9) ["thumbsup", "yes", "awesome", "good", "agree", "accept", "cool", "hand", "like"]
        name: "Thumbs Up Sign"
        non_qualified: undefined
        search: "+1,thumbsup,thumbs,up,sign,yes,awesome,good,agree,accept,cool,hand,like"
        sheet_x: 13
        sheet_y: 38
        short_names: (2) ["+1", "thumbsup"]
        skin_variations:
        1F3FB:
            added_in: "2.0"
            has_img_apple: true
            has_img_facebook: true
            has_img_google: true
            has_img_twitter: true
            image: "1f44d-1f3fb.png"
            non_qualified: null
            sheet_x: 13
            sheet_y: 39
            unified: "1F44D-1F3FB"
            __proto__: Object
        1F3FC: {unified: "1F44D-1F3FC", non_qualified: null, image: "1f44d-1f3fc.png", sheet_x: 13, sheet_y: 40, …}
        1F3FD: {unified: "1F44D-1F3FD", non_qualified: null, image: "1f44d-1f3fd.png", sheet_x: 13, sheet_y: 41, …}
        1F3FE: {unified: "1F44D-1F3FE", non_qualified: null, image: "1f44d-1f3fe.png", sheet_x: 13, sheet_y: 42, …}
        1F3FF: {unified: "1F44D-1F3FF", non_qualified: null, image: "1f44d-1f3ff.png", sheet_x: 13, sheet_y: 43, …}
        text: ""
        unified: "1F44D"
        ...

```

There is the image field under skin variations: `image: "1f44d-1f3fb.png"` - this is the file name that you can use to fetch the emoji file.
